create or replace view view_acc_mast as
select am.acc_code,
       am.title,
       am.acc_name,
       am.parent_code,
       am.codetype,
       am.acc_class_code,
       am.supplier_type,
       am.billtrack,
       am.cbjqty_flag,
       am.entity_code,
       am.div_code,
       am.cename,
       am.add1,
       am.add2,
       am.add3,
       am.city,
       am.pin,
       am.district,
       am.state_code,
       am.country,
       am.stdcode,
       am.phone,
       am.fax,
       am.mobile,
       am.pager,
       am.email,
       am.panno,
       am.stno,
       am.cstno,

       am.area_code,
       am.tds_code,
       am.tds_less,
       am.stax_code,
       am.etax_code,
       am.gpdays,
       am.intrate,
       am.creditlimit,
       am.holiday,
       am.bank_code,
       am.spostr,
       am.eccno,
       am.rangeno,
       am.range_name,
       am.rangeadd1,
       am.rangeadd2,
       am.division,
       am.collector,
       am.user_code,
       am.lastupdate,
       am.oldacc_code,
       am.flag,
       am.add4,
       am.cost_code,
       am.bs_code,
       am.payment_nature,
       am.merged_into,
       am.tin_no,
       am.party_bank_acc_no,
       am.party_bank_name,
       AM.BANK_IFSC_CODE,
       am.acc_type,
       am.emp_code,
       am.acc_sch,
       am.code_level,
       am.acc_status,
       am.div_str,
       am.expense_catg,
       am.ssi_regno,
       am.ssi_reg_date,
       am.ssi_reg_auth,
       am.ssi_reg_validupto,
       am.service_tax_no,
       null sub_ledger_flag,
       broker_code,
       consignee_code,
       geo_code,
       intdays,
       apdays,
       am.inv_acc_flag,
       sm.acc_sch_l1,
       sm.acc_sch_l2,
       sm.acc_sch_name_l1,
       sm.acc_sch_name_l2,
       sm.acc_sch_l3,
       sm.acc_sch_name_l3,
       am.geo_org_code,
       (select parent_code from geo_org_mast where geo_org_code =am.geo_org_code) parent_geo_org_code,
       (select v2.parent_code from geo_org_mast v1, geo_org_mast v2
         where v1.geo_org_code =am.geo_org_code
         and v1.parent_code=v2.geo_org_code) gparent_geo_org_code,
       (select v3.parent_code from geo_org_mast v1, geo_org_mast v2 , geo_org_mast v3
         where v1.geo_org_code =am.geo_org_code
         and v1.parent_code=v2.geo_org_code
         and v2.parent_code=v3.geo_org_code) ggparent_geo_org_code
from   acc_mast am, view_acc_sch_mast sm
where  am.acc_sch = sm.acc_sch_l3

